---
title: "nyc_restaurant Inspection"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    orientation: columns
    vertical_layout: fill
    source_code: embed
---
```{r global, include=FALSE}
library(readr)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
library(flexdashboard)

set.seed(1)

##omit NA
nyc_inspections = read_csv("./data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>% 
  na.omit() 

##clean dataset
nyc_inspections =
  nyc_inspections %>%
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>% 
  mutate(boro = str_to_title(boro),
         inspection_num = row_number()) %>% 
  select(inspection_num, boro, grade, score, critical_flag, dba, cuisine_description, zipcode, grade_date)
```



Column {.sidebar}
-----------------------------------------------------------------------
 
```{r}

# selectInput widget-boro
boros = nyc_inspections %>% distinct(boro) %>% pull()
checkboxGroupInput("boro_choice", label = h3("Select boro for bar plot"),
            choices = boros, selected = c("Manhattan","Brooklyn","Bronx"))


# selectInput widget-year
year = 
  nyc_inspections %>%
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>%  distinct(year) %>% pull()

selectInput("year", label = h3("Select year for line plot"),
            choices = year, selected = "2015")

# sliderInput widget
max_score = 100
min_score = nyc_inspections %>% distinct(score) %>% select(score) %>% na.omit() %>% min()

sliderInput("score_range", label = h3("Choose score of restaurant for box plot"), min = min_score, 
        max = max_score, value = c(10, 40))


# checkbox widget
cuisine_description = nyc_inspections %>% distinct(cuisine_description) %>% pull()

checkboxGroupInput("cuisine_description", label = h3("Choose cuisine type for box plot"),
    choices = cuisine_description, 
    selected = c("American","Korean","Pizza","Chinese"))





```


Row
-----------------------------------------------------------------------

###  bar chart
```{r}
renderPlotly({
  nyc_inspections %>% 
  filter(boro == input$boro_choice) %>% 
  count(boro) %>% 
  plot_ly(x= ~boro, y = ~n, color = ~boro, type = "bar") %>% 
    layout(title = "Number of Restaurant in Different Boros",
           xaxis = list(title = "", tickangle = 45),
         yaxis = list(title = ""),
         margin = list(b = 100),
         barmode = 'group')
  })

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### boxplot
```{r}
renderPlotly({
  nyc_inspections %>% 
    filter(cuisine_description == input$cuisine_description,
           score %in% input$score_range[1]:input$score_range[2]) %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2") %>% 
  layout(title = "the Score Distribution of Different Cuisines",
         xaxis = list(title = "", tickangle = 45),
         yaxis = list(title = ""),
         margin = list(b = 100),
         barmode = 'group',
         showlegend = FALSE)
  })
```

### line plot

```{r}
##plot that shows number of row for each grade date
renderPlotly({
  nyc_inspections %>%
  separate(grade_date, into = c("year", "month", "day"), sep = "-") %>% 
  filter(year == input$year) %>% 
  mutate(month = as.numeric(month)) %>%
  select(inspection_num: month) %>%
  count(year,month) %>% 
  mutate(date = str_c(year,month,"1",sep="-"),
         date = as.Date(date)) %>%
  arrange(date) %>% 
  plot_ly(x = ~date, y = ~n, type = "scatter", mode = "lines") %>% 
  layout(title = "the Number of Restaurant Graded Every Month",
         xaxis = list(title = "time"),
         yaxis = list(title = "number of restaurant"),
         margin = list(b = 100),
         barmode = 'group')
})
```

